### ISSUE TITLE
Can't transform coproduct - Java Enum to Sealed trait

### ISSUE THREAD

**Issue by frevib** [scalalandio/chimney#482] opened 2024-03-20 10:55 UTC
**Checklist**

- [x] I read the documentation at https://chimney.readthedocs.io/ and checked that the functionality exists
- [x] I verified that the behavior for my use case doesn't match the documentation
- [x] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported
  - [x] I checked the https://github.com/scala/bug/issues and haven't found the issue reported there - relevant for Scala 2 compiler crashes, since it might be a bug in the compiler
  - [x] I checked the https://github.com/lampepfl/dotty/issues and haven't found the issue reported there - relevant for Scala 3 compiler crashes, since it might be a bug in the compiler 
- [x] I confirmed that the bug is not related to functionality that was deprecated: lifted transformers (`TransformerF`s) or `unsafeOption` flags
- [x] I believe that this is actual bug, rather than [a question how to use existing features](https://github.com/scalalandio/chimney/discussions)

**Describe the bug**

If we try to convert a Java Enum to a Sealed trait, we get 

```
Chimney can't derive transformation from com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala

SealedTraitScala
  can't transform coproduct instance com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala


SealedTraitScala
  derivation from enumjava: com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala is not supported in Chimney!
```

However, when we put one instance of the Java Enum in scope, e.g. by adding this to the top-level `val enumJava = EnumJava.ONE`, compilation succeeds.

**Reproduction**

We have the Scala file in `src/main/scala`:

```scala
//> using jvm 11
//> using scala 3.3.3
//> using options -
//> using dep io.scalaland::chimney::0.8.5

import com.eventlooopsoftware.javaenum.EnumJava
import io.scalaland.chimney.dsl.*

// uncomment this line and the code will compile...
//val enumJava = EnumJava.ONE

object Main {
  def main(args: Array[String]): Unit = {
    val enumJ: EnumJava = args.headOption.map(it => EnumJava.valueOf(it)).getOrElse(throw new IllegalArgumentException)
    val result = chimneyTransform(enumJ)
    println(result)
  }

  def chimneyTransform(enumJava: EnumJava) = enumJava.transformInto[SealedTraitScala]
}


sealed trait SealedTraitScala
object SealedTraitScala {
  case object ONE extends SealedTraitScala
  case object TWO extends SealedTraitScala
  case object THREE extends SealedTraitScala
}
```

And the Java Enum in the `src/main/java` directory:

```java
package com.eventlooopsoftware.javaenum;

public enum EnumJava {
    ONE, TWO, THREE
}
```

Compilation now fails with `can't transform coproduct instance com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala`.

However if we add `val enumJava = EnumJava.ONE` **somewhere in the file**, compilation succeeds.

Full example is here: https://github.com/frevib/chimney-java-enum-bug-example/blob/main/src/main/scala/Main.scala

**Expected behavior**

Chimney to successfully transform the Java Enum to Scala Sealed trait.

**Actual behavior**

can't transform coproduct instance com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala

**Which Chimney version do you use**

0.8.5 and 1.0.0-M1

**Which platform do you use**

- [x] JVM
- [ ] Scala.js
- [ ] Scala Native

**If you checked JVM**

openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)

**Additional context**

I have an idea that Chimney might not be able to find the Java Enum on the classpath during compile time. I've tried several `CompileOrder`s, but to no use.

**Comment by MateuszKubuszok** [comment] 2024-03-20 12:40
Hello! Thanks for the bug report and the reproduction.

I am not sure when I'll have the time to take a look at this closer. If code compiles when you merely use the definition in scope, I suspect it might be a bug in compiler, that we'd have to workaround (and report).

There was such case in Scala 2 macros - see scala/bug#7755 that we have to work around by [some hack](https://github.com/scalalandio/chimney/blob/9fee3ac46afd36621d8ce595acd68e7a96016524/chimney-macro-commons/src/main/scala-2/io/scalaland/chimney/internal/compiletime/TypesPlatform.scala#L31) - perhaps similar issue exists in Scala 3, we'd have to create a test case for it and work around it (if it's even possible somehow).

@jchyb have you heard of such issues?

**Comment by MateuszKubuszok** [comment] 2024-03-20 13:22
@frevib I tried to reproduce but when I compiled https://github.com/frevib/chimney-java-enum-bug-example/ there was no error. Is there something else I need to do to reproduce?

**Comment by resilica** [comment] 2024-03-20 13:35
I tried and got the same compiler error, i'm on mac M3:


```
 chimney-java-enum-bug-example-main % sbt compile
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/x/Downloads/chimney-java-enum-bug-example-main/project
[info] loading settings for project root from build.sbt ...
[info] set current project to chimney-java-enum-bug-example (in build file:/Users/x/Downloads/chimney-java-enum-bug-example-main/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to /Users/x/Downloads/chimney-java-enum-bug-example-main/target/scala-3.3.3/classes ...
[error] -- Error: /Users/x/Downloads/chimney-java-enum-bug-example-main/src/main/scala/Main.scala:14:85 
[error] 14 |  def chimneyTransform(enumJava: EnumJava) = enumJava.transformInto[SealedTraitScala]
[error]    |                                                                                     ^
[error]    |Chimney can't derive transformation from com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala
[error]    |
[error]    |SealedTraitScala
[error]    |  can't transform coproduct instance com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala
[error]    |
[error]    |
[error]    |SealedTraitScala
[error]    |  derivation from enumjava: com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala is not supported in Chimney!
[error]    |
[error]    |
[error]    |Consult https://chimney.readthedocs.io for usage examples.
[error]    |
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Mar 20, 2024, 2:33:57 PM

```

**Comment by frevib** [comment] 2024-03-20 13:48
@MateuszKubuszok no, just `sbt compile` should give the same error that @resilica has. I’m on sbt 1.9.9.

**Comment by resilica** [comment] 2024-03-20 14:42
I tried it on an intel with the same sbt/scala/java versions and it seems to compile fine as well...

**Comment by frevib** [comment] 2024-03-20 14:45
@MateuszKubuszok @resilica this is really confusing. I'm on Mac m3 (max). I've tried a couple of times and it succeeds, then fails. Here is my output, I've added  `-----OK` and `-----FAILED`:


```jeff@jeffs-MacBook-Pro untitled % sbt compile
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/jeff/tmp/scala_chimney_enum_bug/untitled/project
[info] loading settings for project root from build.sbt ...
[info] set current project to chimney-java-enum-bug-example (in build file:/Users/jeff/tmp/scala_chimney_enum_bug/untitled/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source and 1 Java source to /Users/jeff/tmp/scala_chimney_enum_bug/untitled/target/scala-3.3.3/classes ...
[success] Total time: 2 s, completed Mar 20, 2024, 3:37:15 PM

------OK
jeff@jeffs-MacBook-Pro untitled % sbt
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/jeff/tmp/scala_chimney_enum_bug/untitled/project
[info] loading settings for project root from build.sbt ...
[info] set current project to chimney-java-enum-bug-example (in build file:/Users/jeff/tmp/scala_chimney_enum_bug/untitled/)
[info] sbt server started at local:///Users/jeff/.sbt/1.0/server/a04fc1dbd14c6eb321e8/sock
[info] started sbt server
sbt:chimney-java-enum-bug-example> compile

------OK 
[success] Total time: 0 s, completed Mar 20, 2024, 3:37:28 PM
sbt:chimney-java-enum-bug-example> clean
[success] Total time: 0 s, completed Mar 20, 2024, 3:37:30 PM
sbt:chimney-java-enum-bug-example> compile

------OK
[info] compiling 1 Scala source and 1 Java source to /Users/jeff/tmp/scala_chimney_enum_bug/untitled/target/scala-3.3.3/classes ...
[success] Total time: 2 s, completed Mar 20, 2024, 3:37:59 PM
sbt:chimney-java-enum-bug-example> compile
[success] Total time: 0 s, completed Mar 20, 2024, 3:38:17 PM

------OK
sbt:chimney-java-enum-bug-example> exit
[info] shutting down sbt server
jeff@jeffs-MacBook-Pro untitled % java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
jeff@jeffs-MacBook-Pro untitled % sbt clean
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/jeff/tmp/scala_chimney_enum_bug/untitled/project
[info] loading settings for project root from build.sbt ...
[info] set current project to chimney-java-enum-bug-example (in build file:/Users/jeff/tmp/scala_chimney_enum_bug/untitled/)
[success] Total time: 0 s, completed Mar 20, 2024, 3:38:31 PM
jeff@jeffs-MacBook-Pro untitled % sbt
[info] welcome to sbt 1.9.9 (Eclipse Adoptium Java 17.0.9)
[info] loading project definition from /Users/jeff/tmp/scala_chimney_enum_bug/untitled/project
[info] loading settings for project root from build.sbt ...
[info] set current project to chimney-java-enum-bug-example (in build file:/Users/jeff/tmp/scala_chimney_enum_bug/untitled/)
[info] sbt server started at local:///Users/jeff/.sbt/1.0/server/a04fc1dbd14c6eb321e8/sock
[info] started sbt server
sbt:chimney-java-enum-bug-example> compile
[info] compiling 1 Scala source and 1 Java source to /Users/jeff/tmp/scala_chimney_enum_bug/untitled/target/scala-3.3.3/classes ...
[success] Total time: 2 s, completed Mar 20, 2024, 3:38:38 PM

------OK
sbt:chimney-java-enum-bug-example> clean
[success] Total time: 0 s, completed Mar 20, 2024, 3:38:41 PM
sbt:chimney-java-enum-bug-example> compile
[info] compiling 1 Scala source to /Users/jeff/tmp/scala_chimney_enum_bug/untitled/target/scala-3.3.3/classes ...
[error] -- Error: /Users/jeff/tmp/scala_chimney_enum_bug/untitled/src/main/scala/Main.scala:14:85 
[error] 14 |  def chimneyTransform(enumJava: EnumJava) = enumJava.transformInto[SealedTraitScala]
[error]    |                                                                                     ^
[error]    |Chimney can't derive transformation from com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala
[error]    |
[error]    |SealedTraitScala
[error]    |  can't transform coproduct instance com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala
[error]    |
[error]    |
[error]    |SealedTraitScala
[error]    |  derivation from enumjava: com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala is not supported in Chimney!
[error]    |
[error]    |
[error]    |Consult https://chimney.readthedocs.io for usage examples.
[error]    |
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 0 s, completed Mar 20, 2024, 3:38:44 PM
sbt:chimney-java-enum-bug-example> 

-----FAILED
```

**Comment by MateuszKubuszok** [comment] 2024-03-20 15:00
I am pretty sure at this point that this is a compiler bug which for [this code](https://github.com/scalalandio/chimney/blob/master/chimney-macro-commons/src/main/scala-3/io/scalaland/chimney/internal/compiletime/datatypes/SealedHierarchiesPlatform.scala#L17):

```scala
    def isSealed[A: Type]: Boolean = {
      val flags = TypeRepr.of[A].typeSymbol.flags
      flags.is(Flags.Enum) || flags.is(Flags.Sealed)
    }
```

_sometimes_ returns `false` - even though Java Enums are supposed to return true on this flag check. I think I could work around this code by changing this

```scala
    def parse[A: Type]: Option[Enum[A]] =
      // no need for separate java.lang.Enum handling contrary to Scala 2
      if isSealed[A] then Some(symbolsToEnum(extractSealedSubtypes[A]))
      else None
```

into

```scala

    def parse[A: Type]: Option[Enum[A]] =
      // we should have no need for separate java.lang.Enum handling contrary to Scala 2
      // but there is a bug that makes it necessary
      if isSealed[A] || isJavaEnum[A] then Some(symbolsToEnum(extractSealedSubtypes[A]))
      else None
```

but with no reproduction I can neither test if that would actually help nor report a bug to the Scala 3 compiler team. :/

**Comment by frevib** [comment] 2024-03-20 15:14
@MateuszKubuszok for now the only way to reproduce this, is doing a lot of `clean` and then `compile`, and some “luck”. Maybe a script of doing this many times will reproduce the error in x % of the cases. 

For now I’ll add an Enum instance in scope.

**Comment by frevib** [comment] 2024-03-21 12:55
Thanks for your effort looking into it. For now I'll use the mitigation by placing `val enumJava = EnumJava.ONE` somewher in scope. When I have an idea how to consistently reproduce, I will post here.

**Comment by MateuszKubuszok** [comment] 2024-03-21 13:45
I've made some blind best-effort attempt at https://github.com/scalalandio/chimney/compare/scala-3-java-enum-bugfix?expand=1 - if that would solve the issue, I could merge but, but if it doesn't then I am unfortunately out of options, and I can only hope that it will gets reproduced by someone in Scala 3 compiler team.

**Comment by frevib** [comment] 2024-03-21 14:07
My Intellij (Zinc compile) is consistent in saying this is an error, sbt is not. I could check out and build above branch and see what Intellij has to say. This will not give 100% confidence, but it's something.

**Comment by MateuszKubuszok** [comment] 2024-03-29 16:54
@frevib were you able to check if the workaround helps with anything?

**Comment by frevib** [comment] 2024-03-29 17:57
Yes, adding an instance of the enum in scope solves the problem:

```scala
val enumJava = EnumJava.ONE
```

This can be added top-level or anywhere else in scope, e.g. inside the method.

**Comment by MateuszKubuszok** [comment] 2024-03-29 20:15
And how about the fix from the branch https://github.com/scalalandio/chimney/compare/scala-3-java-enum-bugfix?expand=1 ? Does it help with anything or is it a dead end?

**Comment by frevib** [comment] 2024-03-30 07:27
I did not try that yet. I got a bit stuck in building the Chimney package from source. Are there instructions on how to build Chimney? I will do it asap then.

**Comment by MateuszKubuszok** [comment] 2024-03-30 09:05
I think `RELEASE=true sbt chimneyMacroCommons3/publishLocal chimney3/publishLocal` should do the trick.

**Comment by frevib** [comment] 2024-03-31 17:49
Unfortunately I cannot give a definitive answer. I've tried the new `1.0.0-M2` build and it gave the same error. Then I reverted back to `0.8.5` and it compiled successfully, at least 10 times in a row. I've tried many other things for a hour, and could not find any consistent result. I found some odd behaviour in Intellij though. After a `sbt clean` the compiled classes are deleted from the `target` directory, and then automatically return (see image). 

At this point I don't know any more. Intellij's UI keeps saying that `Chimney can't derive transformation from com.eventlooopsoftware.javaenum.EnumJava to SealedTraitScala`, but `sbt compile` does work most of the time now. It seems like it's something very weird with my Intellij or a compiler bug that does does not surface on Easter Sunday 😕 .

That's all I can do for now. 
<img width="440" alt="Screenshot 2024-03-31 at 19 30 01" src="https://github.com/scalalandio/chimney/assets/5623111/7cb9464c-e6d9-483f-b86f-a9f0e3e9e4a4">


@resilica can you try one more time? If no one else has any problems we can close this issue.

**Comment by MateuszKubuszok** [comment] 2024-04-02 12:16
`1.0.0-M2` did not have the workaround merged (and neither did `1.0.0-M3` nor `1.0.0-M4` - I don't want to introduce a complexity that I am not sure would be justified), so at best it shows that nothing got fixed accidentally in the meantime. The workaround would have to tested by:

```bash
git clone https://github.com/scalalandio/chimney.git
cd chimney
git checkout scala-3-java-enum-bugfix
export RELEASE=true # turn off -Xfatal-warnings which fails scaladoc (sic!) generation
sbt chimneyMacroCommons3/publishLocal chimney3/publishLocal
# then use chimney in version 1.0.0-M2-2-g775e2ce6-SNAPSHOT
```

However, I am almost certain that it would be some weird bug in the compiler. I might have even more certainty (or rule that out) if failed logs were enriched with `.enableMacrosLogging` and the info output of the failed line (it will not be shown in IJ if there is an error at the same position, so the bug would have to be reproduced in console).

**Comment by frevib** [comment] 2024-04-05 10:56
Yes, `scala-3-java-enum-bugfix` is used.

I also had to include the java-collections: 

`RELEASE=true sbt chimneyMacroCommons3/publishLocal chimney3/publishLocal chimneyJavaCollections3/publishLocal`

Then use the `1.0.0-M2-5-g5dc1807-SNAPSHOT` version.

The error still occurs at random times. 95% of the times it works though. I was able to reproduce it for a while by deleting the `target` directory, and then running `compile` in the sbt cli, but later it just constantly worked. I have absolutely no idea what's going on here.

**Comment by MateuszKubuszok** [comment] 2024-04-05 12:35
If the workaround didn't help then I am not sure anymore where the bug occurs. If it's not the flags, then maybe the `.children` property, but at this point I am completely unable to fix that on the library's side. Either someone from the compiler team would be able to reproduce it or it's unfixable.

**Comment by frevib** [comment] 2024-04-05 12:48
Thx for looking into it.

@resilica where you able to test?

**Comment by MateuszKubuszok** [comment] 2024-04-25 12:27
Since there is nothing we can do do fix this, and the only solution I can see is fixing it in the compiler, I'll close it now.

**Closed by MateuszKubuszok** 2024-04-25 12:27 UTC
Labels: bug, bug in compiler
