### ISSUE TITLE
Unexpected arity mismatch when mixing Tuple with `enableOptionDefaultsToNone`

### ISSUE THREAD

**Issue by coreyoconnor** [scalalandio/chimney#434] opened 2023-11-13 19:59 UTC
**Checklist**
- [X ] I read the documentation at https://chimney.readthedocs.io/ and checked that the functionality exists
- [ X] I verified that the behavior for my use case doesn't match the documentation
- [X ] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported
- [ X] I confirmed that the bug is not related to functionality that was deprecated: lifted transformers (`TransformerF`s) or `unsafeOption` flags
- [X ] I believe that this is actual bug, rather than a question how to use existing features

**Describe the bug**

Given the statement: `You can use all the flags, renames, value provisions, and computations that are available to case classes, Java Beans and so on.`

I'd expect to be able to use `enableOptionDefaultsToNone` with `Tuple`s. However, chimney fails to derive the transformation and reports an arity mismatch. 

**Reproduction**

consider the following example:

```
scala> case class MyClass(x: Int, y: Int, z: String, zz: Option[Int])
class MyClass

scala> import io.scalaland.chimney.dsl._
import io.scalaland.chimney.dsl._

scala> (1, 2, "asd").into[MyClass].enableOptionDefaultsToNone.transform
                                                              ^
       error: Chimney can't derive transformation from scala.Tuple3[scala.Int, scala.Int, java.lang.String] to MyClass

       MyClass
         source tuple scala.Tuple3[scala.Int, scala.Int, java.lang.String] is of arity 3, while target type MyClass is of arity 4; they need to be equal!


       Consult https://chimney.readthedocs.io for usage examples.

scala> case class OtherClass(x: Int, y: Int, z: String)
class OtherClass

scala> OtherClass(1, 2, "asd").into[MyClass].enableOptionDefaultsToNone.transform
val res4: MyClass = MyClass(1,2,asd,None)
```

**Expected behavior**

The transformation from `Tuple` to work the same as `OtherClass`.

**Actual behavior**
A description showing what happened: ideally a copy of compiler error, example of wrong value generated, stack trace and message of thrown exception.

**Which Chimney version do you use**
Version you used for confirming bug with a snippet.

**Which platform do you use**
- [ ] JVM
- [ ] Scala.js
- [ ] Scala Native

**If you checked JVM**
Which JVM distribution do you use (you can provide `java -version` output).

**Additional context**

**Comment by MateuszKubuszok** [comment] 2023-11-15 12:22
Thanks for the report and reproduction!

I haven't done any deeper investigation, but I think this could be fixed by:

- taking this check: https://github.com/scalalandio/chimney/blob/87a2e7f5e56972c66a9e630ac3af3facf58d7d74/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/rules/TransformProductToProductRuleModule.scala#L111
- moving it here: https://github.com/scalalandio/chimney/blob/87a2e7f5e56972c66a9e630ac3af3facf58d7d74/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/rules/TransformProductToProductRuleModule.scala#L123
- so that generating error for mismatched tuple arity would be done after attempting to use default values
- then adding an appropriate test to https://github.com/scalalandio/chimney/blob/87a2e7f5e56972c66a9e630ac3af3facf58d7d74/chimney/src/test/scala/io/scalaland/chimney/IssuesSpec.scala to prevent any regression in the future
- maybe update the error message and docs to reflect that arity doesn't have to be perfectly aligned if overrides will the differences?

I do not have the capacity to fix this myself anytime soon, but if anyone would be interested to try to do it and create a PR, I could review and merge it and maybe even publish release (since around 0.8.2 we started using GH Workflows for publishing releases and snapshots, so it is not as much of a ceremony as it used to).

**Comment by coreyoconnor** [comment] 2023-11-15 22:40
Rock on! Thanks for the details :) I may be able to roll with this. I have some time coming up to try.

**Comment by MateuszKubuszok** [comment] 2023-11-15 23:26
Thank you! Feel free to ask if there will be any trouble.

**Comment by coreyoconnor** [comment] 2023-11-17 00:42
Opened a PR. The changes *mostly* make sense to me. I'm guessing `useFallbackValues` at some point recurses?

**Closed** 2023-11-20 10:52 UTC
Labels: bug, low hanging fruit

**Comment by MateuszKubuszok** [comment] 2023-11-20 10:59
Everything's looking good :)

>  I'm guessing `useFallbackValues` at some point recurses?

Most of the time when we are converting something into something else we have to use recursion - to make sure we are converting one thing into another the way users' expecting - but default/fallback values are used only if there is no source provided (manually or by matching fields) and (by definition) they are always in the desired format. We can use them as they are, with no extra work, so `useFallbackValues` doesn't have to call `deriveRecursiveTransformationExpr`.

**Comment by MateuszKubuszok** [comment] 2023-11-20 11:51
Changes released in 0.8.3 :), thank you for the fix!
