### ISSUE TITLE
Handling nested generics with [_]

### ISSUE THREAD

**Issue by Teudimundo** [scalalandio/chimney#204] opened 2021-02-25 23:34 UTC
I have this two classes:

```scala

final case class WrapperProto(position: AbstractPositionProto)
final case class Wrapper[T](position: AbstractPosition[T])
```

And I'm trying to derive a transformer between the two such as:

```scala
implicit val apf: Transformer[AbstractPosition[_], AbstractPositionProto] = ...
 
val v = Transformer.derive[Wrapper[_], WrapperProto]
```

the compilation fails with the following error:

```
Chimney can't derive transformation from ....Wrapper[_] to ....WrapperProto

....WrapperProto
  position: ....AbstractPositionProto - can't derive transformation from position: ....AbstractPosition in source type .....Wrapper
```

Note that everything works fine with the following code:

```scala

final case class WrapperProto(position: AbstractPositionProto)
final case class Wrapper(position: AbstractPosition[_])

implicit val apf: Transformer[AbstractPosition[_], AbstractPositionProto] = ...
 
val v = Transformer.derive[Wrapper, WrapperProto]
```

**Comment by MateuszKubuszok** [comment] 2023-07-31 17:03
The reason Chimney macro displays this message is because implicit summoning (which search for `Transformer[AbstractPosition[_], AbstractPositionProto]`) returns nothing.

Investigating why that happens I created the [following Scastie](https://scastie.scala-lang.org/MateuszKubuszok/FQMtaK6wTKCjnd7wcnszWg/7):

```scala
trait Transformer[From, To] {
  def transform(src: From): To
}

class AbstractPositionProto(s: String)
class AbstractPosition[T](val t: T)

final case class WrapperProto(position: AbstractPositionProto)
final case class Wrapper[T](position: AbstractPosition[T]) {

  def getImplicit(implicit t: Transformer[AbstractPosition[T], AbstractPositionProto]): Unit = ()
}

implicit val apf: Transformer[AbstractPosition[_], AbstractPositionProto] =
  ap => new AbstractPositionProto(ap.t.toString)

val test: Wrapper[_] = Wrapper(new AbstractPosition("test"))

test.getImplicit
```

This code tries to find implicit `Transformer[AbstractPosition[T], AbstractPositionProto]` where `T` is propagated from `Wrapper[T]` and set up as existential type, just like in the repo but skipping macros, it only has 1 implicit to find and one type parameter to propagate from wrapper with existential type.

Pure Scala fails to do so. The compiler cannot find the implicit for `test.getImplicit` even though you want it to use implicit defined 5 lines above. 

I'm afraid the problem is not in the macro but in how the compiler treats existentials and apparently it considers manually applied `_` as different type than `_` propagated from the wrapper, so we would have to implement in the library the mechanism that the compiler doesn't provide. And it might be intentional. I checked that on Scala 3 this implicit also [cannot be found](https://scastie.scala-lang.org/MateuszKubuszok/FQMtaK6wTKCjnd7wcnszWg/8).

What is more, it fails to compile if you attempt to [pass that value yourself](https://scastie.scala-lang.org/MateuszKubuszok/FQMtaK6wTKCjnd7wcnszWg/9):

```scala
test.getImplicit(apf)
// Found:    (Playground.apf :
//   Playground.Transformer[Playground.AbstractPosition[?],
//     Playground.AbstractPositionProto]
// )
// Required: Playground.Transformer[Playground.AbstractPosition[Playground.test.T],
//   Playground.AbstractPositionProto]
```

So unfortunately this is a won't fix situation.

**Closed by MateuszKubuszok** 2023-07-31 17:03 UTC
