### ISSUE TITLE
Increased compile time since 1.2.0

### ISSUE THREAD

**Issue by nox213** [scalalandio/chimney#629] opened 2024-10-17 02:27 UTC
**Checklist**

- [x] I read the documentation at https://chimney.readthedocs.io/ and checked that the functionality exists
- [x] I verified that the behavior for my use case doesn't match the documentation
- [x] I checked the https://github.com/scalalandio/chimney/issues and haven't found the issue reported
  - [x] I checked the https://github.com/scala/bug/issues and haven't found the issue reported there - relevant for Scala 2 compiler crashes, since it might be a bug in the compiler
  - [x] I checked the https://github.com/lampepfl/dotty/issues and haven't found the issue reported there - relevant for Scala 3 compiler crashes, since it might be a bug in the compiler 
- [x] I confirmed that the bug is not related to functionality that was deprecated: lifted transformers (`TransformerF`s) or `unsafeOption` flags
- [x] I believe that this is actual bug, rather than [a question how to use existing features](https://github.com/scalalandio/chimney/discussions)

**Describe the bug**

We have a large project with a lot of transformers.
After upgrading from 1.1.0 to 1.2.0, we noticed the compile time went up consistently by around 1 minute (from 5min before to 6min after) without any other changes.
We tried each individual snapshot between 1.1.0 and 1.2.0 and found that the problem starts after this PR was merged: https://github.com/scalalandio/chimney/pull/547 (snapshot `1.1.0-19-gcc41c49-SNAPSHOT`).
Note that we are not using `Iso` and `Codec` at all so it looks like this change had a side effect on overall compile speed.

**Reproduction**

Sadly we have none to share as it is a large closed source project.
It is just a lot of transformers and partial transformers for a lot of types.

**Expected behavior**

Similar compile time as 1.1.0.

**Actual behavior**

Slower compile time.

**Which Chimney version do you use**

1.2.0 (same issue with 1.5.0 and all versions after 1.2.0).

**Which platform do you use**

- [x] JVM
- [ ] Scala.js
- [ ] Scala Native

**If you checked JVM**

JDK 21, temurin

**Additional context**

Scala version is 2.13.14.

**Comment by MateuszKubuszok** [comment] 2024-10-17 08:32
I'm afraid this cannot be fixed without removing support for `Iso`/`Codec` which would be breaking change.

It's not a bug but a consequence of how implicits work and how one adds a support to new types through them, but the impact on compile time is something that would be interesting to the compiler team. CC @jchyb

**Closed by MateuszKubuszok** 2024-10-17 08:32 UTC
Labels: bug

**Comment by nox213** [comment] 2025-05-09 00:49
@MateuszKubuszok FYI, I tested with Scala 3.6.4 and noticed that the performance issue still exists.

**Comment by MateuszKubuszok** [comment] 2025-05-09 08:20
@nox213 as long as we have `Iso`/`Codec`, from which we can extract `Transformer`s/`PartialTransformer`s, there will be some performance penalty. I tried doing something about it in 2.0.0-M1, but if that didn't help then it's impossible to improve the performance without throwing away the existing functionality. And we are not removing that functionality.

**Comment by ghostdogpr** [comment] 2025-05-09 08:34
(I work with @nox213)
That is quite unfortunate as this change literally increases the compile time spent by Chimney by 100% in our project (which has a lot of transformations). We've been stuck on 1.1.0 because of it but staying on an old version is not really sustainable. I wonder why we are the only one noticing it or if there is a special pattern we're using that should be avoided 😄 
We will give a try to 2.0.0-M1.

**Comment by MateuszKubuszok** [comment] 2025-05-09 09:11
I'd assume that it might be because most people do not use Chimney to its fullest.

When I look at the downloads from March:

 * on Scala 3, 80% downloads are 1.2.0+ - so most people keep it up to date
 * on Scala 2.13, 55% are 1.2.0+ - some are on 0.8.5, so at least people use the Chimney after 0.8.x rewrite
 * on Scala 2.12 only 27% downloads are 0.8.0+ (!!!) - 50% are 0.5.3, 0.6.1, 0.7.5, we could drop 2.12 and probably nobody would notice
 * currently there is 2x as many Scala 3 as there is Scala 2.12 users... but there is 4x as many Scala 2.13 users as Scala 3 users - while 3 is rising and 2.12 is declining, the majority are still 2.13 users who are scattered across all the versions

My interpretation is that people see little incentive to update to get new features and bugfixes, as they (believe that they) don't need any new features, and worked around the bugs.

Also many people are also hostile to macros, so they would avoid libraries like Chimney in the first place, and when they use it it's only in a few places. When I looked for Chimney usage on GitHub most project only imported Chimney in 1-2 files.

If not for the people telling me in person that they use the library, I would have no evidence that anyone uses it intensively in any project, so perhaps there are other projects with the same issue as your but only you bothered to provide any feedback.

**Comment by ghostdogpr** [comment] 2025-05-13 02:07
Tested with 2.0.0-M1 but it's still around 1min slower than before 1.2.0.

We indeed use Chimney intensively, to transform types generated by ScalaPB from/to our domain logic entities, and there are thousands of such types.

**Comment by MateuszKubuszok** [comment] 2025-05-28 10:06
The issue comes from how implicits works:

 - if we want to have something like Codec/Iso (working similar to Circe's Codec), we need a new type class, which is just a tuple of transformers
 - every time we look for implicit `Transformer`/`PartialTransformer`, we not only have to check for the implicit transformer, but also we have to take a look if there is `Codec`/`Iso` that could contain such transformer
 - so every time we need to check if transformer exists we might end up looking for: Transformer, Codec and Iso, in the scope and the companion object of every type involved
 - we cannot selectively decide that in one place we would us it and in another we wouldn't because it would break the feature for its users

and we cannot just remove the feature because people use it.

We can start by verifying if removing Codec/Iso from the equation really helps, by:

 - commenting out the lines that summon Codecs/Iso
 - publishing Chimney locally
 - using the snapshot
 - checking if snapshot version solves the problem

If that helps, we can:

 - on [`2.0.0-development` branch](https://github.com/scalalandio/chimney/tree/2.0.0-development)
 - on Scala 3 only - because we rely on `Expr.summonIgnoring`
 - [add a flag](https://github.com/scalalandio/chimney/blob/master/CONTRIBUTING.md#contributing-code) for global disabling of Codec/Iso usage
   - it should be enough to only expose it via https://github.com/scalalandio/chimney/blob/be072a8f9b5fbb26c1db98dae7860b8a20f5ae7e/chimney/src/main/scala/io/scalaland/chimney/internal/compiletime/derivation/transformer/Configurations.scala#L173  without adding a new method to DSL, although by adding it to DSL (on Scala 3 only) it could be tested
   - Scala-3 only test could be added e.g. to https://github.com/scalalandio/chimney/blob/2.0.0-development/chimney/src/test/scala-3/io/scalaland/chimney/IssuesScala3Spec.scala
 - we could modify https://github.com/scalalandio/chimney/blob/be072a8f9b5fbb26c1db98dae7860b8a20f5ae7e/chimney/src/main/scala-3/io/scalaland/chimney/internal/compiletime/derivation/transformer/DerivationPlatform.scala#L53 and https://github.com/scalalandio/chimney/blob/be072a8f9b5fbb26c1db98dae7860b8a20f5ae7e/chimney/src/main/scala-3/io/scalaland/chimney/internal/compiletime/derivation/transformer/DerivationPlatform.scala#L71 to take an implicit `TransformationContext` and check for a flag (signature would have to be changed for all Scala versions, implementation only for Scala 3)

When the proper fix works, it could be documented.

Ideally, such things should work the same on Scala 2 and 3, but there is no Expr.summonIgnoring counterpart in Scala 2, so for now we can try to fix only Scala 3.

**Comment by nox213** [comment] 2025-05-29 01:48
Thanks for the detail explanation. We will look into it.
